[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on = "Enter"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
